"""Dump MySQL `ideaweave` -> deploy/ideaweave_{schema,data,full}.sql.

用 pymysql（纯 Python）而不是本机 mysqldump：MySQL 9.x 客户端已移除
mysql_native_password 插件，连不上老版本服务端；pymysql 在客户端实现了该认证。

用法:
    cd backend && .venv/bin/python3 scripts/dump_mysql.py
"""

from __future__ import annotations

import sys
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path

import pymysql
from pymysql.converters import escape_string

BACKEND = Path(__file__).resolve().parents[1]
PROJECT = BACKEND.parent
OUT_DIR = PROJECT / "deploy"
ENV = BACKEND / ".env"

# 按外键依赖顺序插入（同 scripts/migrate_sqlite_to_mysql.py）
INSERT_ORDER = [
    "users",
    "personas",
    "user_settings",
    "inspirations",
    "topics",
    "idea_sessions",
    "scripts",
    "calendar_events",
]

CHARSET = "utf8mb4"

DEFAULT_URL = "mysql+pymysql://root:123456@10.23.36.149:3306/ideaweave?charset=utf8mb4"


def load_url() -> str:
    if ENV.exists():
        for line in ENV.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line.startswith("DATABASE_URL="):
                val = line.split("=", 1)[1].strip()
                if val:
                    return val
    return DEFAULT_URL


def sql_literal(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, Decimal):
        return str(v)
    if isinstance(v, datetime):
        return "'" + v.strftime("%Y-%m-%d %H:%M:%S") + "'"
    if isinstance(v, date):
        return "'" + v.strftime("%Y-%m-%d") + "'"
    if isinstance(v, bytes):
        v = v.decode("utf-8", errors="replace")
    if not isinstance(v, str):
        v = str(v)
    return "'" + escape_string(v) + "'"


# 导出时脱敏的列：避免把 API Key 等密钥写进 SQL 文件
REDACT_COLS = {"user_settings": {"llm_api_key"}}


def _redact_value(table: str, col: str, v):
    if v and table in REDACT_COLS and col in REDACT_COLS[table]:
        return "sk-REDACTED"
    return v


def main() -> int:
    from sqlalchemy.engine.url import make_url

    url = make_url(load_url())
    conn = pymysql.connect(
        host=url.host,
        port=url.port or 3306,
        user=url.username,
        password=url.password or "",
        database=url.database,
        charset=CHARSET,
        connect_timeout=8,
    )

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    header = [
        f"-- Dump of `{url.database}`",
        "-- Generated by scripts/dump_mysql.py (pymysql)",
        f"-- MySQL host: {url.host}:{url.port or 3306}",
        "",
    ]

    try:
        with conn.cursor() as cur:
            cur.execute("SHOW TABLES")
            tables = [r[0] for r in cur.fetchall()]
            ordered = [t for t in INSERT_ORDER if t in tables]
            ordered += [t for t in tables if t not in INSERT_ORDER]

            # ---- schema ----
            schema = list(header) + [
                "SET NAMES utf8mb4;",
                "SET FOREIGN_KEY_CHECKS=0;",
                "",
            ]
            for t in ordered:
                cur.execute(f"SHOW CREATE TABLE `{t}`")
                row = cur.fetchone()
                ddl = row[1] if len(row) > 1 else row[0]
                schema.append(f"DROP TABLE IF EXISTS `{t}`;")
                schema.append(ddl + ";")
                schema.append("")
            schema.append("SET FOREIGN_KEY_CHECKS=1;")

            # ---- data ----
            data = list(header) + [
                "SET NAMES utf8mb4;",
                "SET FOREIGN_KEY_CHECKS=0;",
                "",
            ]
            for t in ordered:
                cur.execute(f"SELECT * FROM `{t}`")
                cols = [d[0] for d in cur.description]
                rows = cur.fetchall()
                if not rows:
                    continue
                col_sql = ", ".join(f"`{c}`" for c in cols)
                data.append(f"-- {t}: {len(rows)} rows")
                for row in rows:
                    vals = ", ".join(sql_literal(_redact_value(t, col, v)) for col, v in zip(cols, row))
                    data.append(f"INSERT INTO `{t}` ({col_sql}) VALUES ({vals});")
                data.append("")
            data.append("SET FOREIGN_KEY_CHECKS=1;")

            # ---- full = schema(带 DROP/CREATE) + data ----
            full = list(header) + [
                "SET NAMES utf8mb4;",
                "SET FOREIGN_KEY_CHECKS=0;",
                "",
            ]
            for t in ordered:
                cur.execute(f"SHOW CREATE TABLE `{t}`")
                row = cur.fetchone()
                ddl = row[1] if len(row) > 1 else row[0]
                full.append(f"DROP TABLE IF EXISTS `{t}`;")
                full.append(ddl + ";")
                full.append("")
            for t in ordered:
                cur.execute(f"SELECT * FROM `{t}`")
                cols = [d[0] for d in cur.description]
                rows = cur.fetchall()
                if not rows:
                    continue
                col_sql = ", ".join(f"`{c}`" for c in cols)
                full.append(f"-- {t}: {len(rows)} rows")
                for row in rows:
                    vals = ", ".join(sql_literal(_redact_value(t, col, v)) for col, v in zip(cols, row))
                    full.append(f"INSERT INTO `{t}` ({col_sql}) VALUES ({vals});")
                full.append("")
            full.append("SET FOREIGN_KEY_CHECKS=1;")

        (OUT_DIR / "ideaweave_schema.sql").write_text("\n".join(schema) + "\n", encoding="utf-8")
        (OUT_DIR / "ideaweave_data.sql").write_text("\n".join(data) + "\n", encoding="utf-8")
        (OUT_DIR / "ideaweave_full.sql").write_text("\n".join(full) + "\n", encoding="utf-8")

        print("tables:", ordered)
        print(f"schema: {len(schema)} lines")
        print(f"data:   {len(data)} lines")
        print(f"full:   {len(full)} lines")
    finally:
        conn.close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
