-- Dump of `ideaweave`
-- Generated by scripts/dump_mysql.py (pymysql)
-- MySQL host: 10.23.36.149:3306

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password_hash` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `active_persona_id` int DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ix_users_username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `personas`;
CREATE TABLE `personas` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `template_key` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `style_desc` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `audience` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `video_format` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `taboos` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `sample_tone` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `zone` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content_style` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `update_freq` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `comment_style` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `skill_prompt` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `skill_brief_json` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `skill_generated_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_personas_user_id` (`user_id`),
  CONSTRAINT `personas_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `user_settings`;
CREATE TABLE `user_settings` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `llm_base_url` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `llm_model` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `llm_api_key` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`),
  CONSTRAINT `user_settings_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `inspirations`;
CREATE TABLE `inspirations` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `raw_text` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `source_note` text COLLATE utf8mb4_unicode_ci,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_inspirations_user_id` (`user_id`),
  CONSTRAINT `inspirations_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `topics`;
CREATE TABLE `topics` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `inspiration_id` int DEFAULT NULL,
  `title` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `highlights` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `feasibility` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `cost_note` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `why` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `source` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` datetime NOT NULL,
  `priority` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT 'mid',
  `tags` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  KEY `inspiration_id` (`inspiration_id`),
  KEY `ix_topics_user_id` (`user_id`),
  CONSTRAINT `topics_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `topics_ibfk_2` FOREIGN KEY (`inspiration_id`) REFERENCES `inspirations` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `idea_sessions`;
CREATE TABLE `idea_sessions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `topic_id` int DEFAULT NULL,
  `vague_idea` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `ideas_json` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `selected_index` int DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `saved_json` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  KEY `topic_id` (`topic_id`),
  KEY `ix_idea_sessions_user_id` (`user_id`),
  CONSTRAINT `idea_sessions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `idea_sessions_ibfk_2` FOREIGN KEY (`topic_id`) REFERENCES `topics` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `scripts`;
CREATE TABLE `scripts` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `topic_id` int DEFAULT NULL,
  `idea_session_id` int DEFAULT NULL,
  `outline` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `shot_list` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `comments_text` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `script_json` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `cover_prompts_json` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `risks_json` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `topic_id` (`topic_id`),
  KEY `idea_session_id` (`idea_session_id`),
  KEY `ix_scripts_user_id` (`user_id`),
  CONSTRAINT `scripts_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `scripts_ibfk_2` FOREIGN KEY (`topic_id`) REFERENCES `topics` (`id`),
  CONSTRAINT `scripts_ibfk_3` FOREIGN KEY (`idea_session_id`) REFERENCES `idea_sessions` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `calendar_events`;
CREATE TABLE `calendar_events` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `title` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `start_date` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `end_date` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `location` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL,
  `vlog_fit` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `commercial` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `raw_text` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `source` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_calendar_events_user_id` (`user_id`),
  CONSTRAINT `calendar_events_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=63 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS=1;
